archive/urls.py
from django.contrib import admin
from django.urls import path
from file.views import HomeView
from django.conf import settings
from django.urls import path, include, reverse_lazy
from account.views import LoginView, RegisterView 
from django.contrib.auth.views import  LogoutView
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('account/', include('account.urls', namespace='user')),
    path('file/', include('file.urls', namespace='file')),
 
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('register/',RegisterView.as_view(), name='register'),
 
]
urlpatterns.extend(
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

file/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.static import serve
from . import views

app_name='file'

urlpatterns = [
    path('', views.PostView.as_view(), name='post'),
    path('admin-list/', views.PostAdminView.as_view(), name='post-admin'),
    path('memo/', views.Memorandum.as_view(), name='memo'),
    path('memo-admin/', views.MemoAdmin.as_view(), name='memo-admin'),
    path('curriculum/', views.Curriculum.as_view(), name='curriculum'),
    path('Syllabus', views.Syllabus.as_view(), name='syllabus'),
    path('<title>/', views.PostDetailView.as_view(), name='detail'),
    path('memo/<title>/', views.MemoDetailView.as_view(), name='memo-detail'),
    path('approve-file/<int:pk>/', views.AdminAproval, name='file-approve'),
    path('approve-memo/<int:pk>/', views.MemoApprove, name='memo-approve'),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
   
#    path('post/', views.PdfUploadView.as_view(), name='post')
]

file/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.conf import settings
from .validators import validate_file_extention
from django.urls import reverse
from django.db.models import Q
from account.models import User
from .utils import unique_slug_generator
from account.models import Course,Department
User = settings.AUTH_USER_MODEL

YEAR = (
    ('1st', 'Firs Year'),
    ('2nd', 'Second Year'),
    ('3rd', 'Third Year'),
    ('4rt', 'Fourth Year'),
    ('grad', 'Graduate'),
    
)

TYPE = (
 
    ('Research', 'Research'),
    ('Syllabus', 'Syllabus'),
    ('Paascu', 'Paascu'),
) 
class FileQuerySet(models.query.QuerySet):
    def search(self,query): 
        if query:
            query = query.strip()
            return self.filter(
                Q(title__icontains=query)
 

                ).distinct()
        return self
 
class FileManager(models.Manager):
    def get_queryset(self):
        return FileQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)



def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

class PathAndRename(object):

    def __init__(self,sub_path):
        self.path = sub_path

    def __call__(self,instance, filename):
        ext = filename.split('.')[-1]

        if instance.pk:
            filename = '{}.{}'.format(instance.pk,ext)
        else:
            filename = '{}.{}'.format(instance.pk,ext)
        return os.path.join(self.path, filename)

path_and_rename = PathAndRename("media/file/")

class Author(models.Model):
    lastname           = models.CharField(max_length=100)
    firstname          = models.CharField(max_length=100)
    middlename         = models.CharField(max_length=100)
    email              = models.EmailField(max_length=254)
    department         = models.ForeignKey(Department, null=True,on_delete=models.CASCADE)
    course             = models.ForeignKey(Course, null=True,on_delete=models.CASCADE)
    Year               = models.CharField(max_length=6, choices=YEAR, blank=True, default=True)
    date_created       = models.DateTimeField(auto_now_add = True)
    date_modified      = models.DateTimeField(auto_now = True)
    slug               = models.SlugField(null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.lastname)

    class Meta:
        ordering = ['-id']

class Post(models.Model):
    title          = models.CharField(max_length=100)
    type_documents = models.CharField(max_length=30, choices=TYPE , blank=True, default=True)   
    description    = models.TextField(null=True, blank=True)
    author         = models.ForeignKey(Author, null=True,on_delete=models.CASCADE)
    date_uploaded  = models.DateTimeField(auto_now_add=True)
    modified       = models.DateTimeField(auto_now=True)
    file           = models.FileField(null=True,validators=[PathAndRename] )
 
    
    approve        = models.BooleanField(default=False)
    remove         = models.BooleanField(default=False)

    objects = FileManager()

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        ordering = ['-date_uploaded']

class Memo(models.Model):
    user           = models.ForeignKey(User, null=True, blank=True, on_delete = models.CASCADE)
    title          = models.CharField(max_length=100)
    content        = models.FileField(upload_to="memo", null=True)
    description    = models.TextField(null=True, blank=True)
    date_uploaded  = models.DateTimeField(auto_now_add=True)
    modified       = models.DateTimeField(auto_now=True)


    approve        = models.BooleanField(default=False)
    remove         = models.BooleanField(default=False)

    objects        = FileManager()
    
    def __str__(self):
        return '{}'.format(self.title)
        
    @property
    def slug_title(self):
        return '{}'.format(self.title)

    class Meta:
        ordering = ['-date_uploaded']

file/forms.py
from django import forms
from .models import Post,Department,Author, Course,Memo
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.forms.widgets import FileInput

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title',
        		  'type_documents',
        		  'description',
        		  'author',
        		  'file')
        widgets = {
            'desciption': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
                })
        }

class ApprovePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('approve',
        		  'remove',
        		  )
 
class DepartmentForm(forms.ModelForm):
	class Meta:
		model = Department
		fields = ('department_code','department_description')

class CourseForm(forms.ModelForm):
	class Meta:
		model = Course
		fields = ('course_code','course_description')

class AuthorForm(forms.ModelForm):
	class Meta:
		model = Author
		fields = ('lastname',
				  'firstname',
				  'middlename',
				  'department',
				  'course',
				  'Year')

class MemoForm(forms.ModelForm):
	class Meta:
		model = Memo
		fields = ('title','content')

class ApproveMemoForm(forms.ModelForm):
    class Meta:
        model = Memo
        fields = ('approve',
        		  'remove',
        		  )
 

file/views.py
import os
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import (LoginRequiredMixin,PermissionRequiredMixin)
from django.shortcuts import render, Http404, get_object_or_404, redirect
from django.views.generic import (ListView,DetailView,CreateView,UpdateView, View)
from django.contrib.auth.mixins import (LoginRequiredMixin,PermissionRequiredMixin)
from django.contrib.auth import get_user_model
from .models import (Post, Memo, Department, Author, Course,)
from .forms import (PostForm,ApproveMemoForm,ApprovePostForm, DepartmentForm, CourseForm, AuthorForm)
 
class HomeView(View):
    def get(self, request, *args, **kwargs):
        file = Post.objects.filter(type_documents='Research').order_by("-title")[:9]
        context = {'file':file,}
        return render(request, "home.html", context)

class  Memorandum(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        file = Memo.objects.all().order_by("-date_uploaded").search(query)

        if file.exists():
            return render(request, "file/memo.html",{'file':file})
        return render(request, "file/memo.html",{'file':file})

class MemoDetailView(LoginRequiredMixin,View):
    def get(self, request, title, *args, **kwargs):
        file = get_object_or_404(Memo, title=title)
        context = {'file':file,}
        return render(request, "file/memo_detail.html", context)

class  Syllabus(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        file = Post.objects.filter(type_documents='Syllabus').order_by("-title").search(query)
        
        if file.exists():
            return render(request, "file/syllabus.html",{'file':file})
        return render(request, "file/syllabus.html",{'file':file})

class Curriculum(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        file = Post.objects.filter(type_documents='Paascu').order_by("-title").search(query)
        
        if file.exists():
            return render(request, "file/curriculum.html",{'file':file})
        return render(request, "file/curriculum.html",{'file':file})

class PostView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        file = Post.objects.filter(type_documents='Research').order_by("-title").search(query)
        
        if file.exists():
            return render(request, "file/file_list.html",{'file':file})
        return render(request, "file/file_list.html",{'file':file})

class PostDetailView(LoginRequiredMixin,View):
    def get(self, request, title, *args, **kwargs):
        file = get_object_or_404(Post, title=title)
        context = {'file':file,}
        return render(request, "file/file_detail.html", context)


class AuthorView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        author = Author.objects.all().order_by("-title").search(query)
        
        if author and qs.exists():
            return render(request, "author_list.html",{'author':author})
        return render(request, "author_list.html",{'author':author})

class AuthorDetailView(LoginRequiredMixin,View):
    def get(self, request, lastname, *args, **kwargs):
        author = get_object_or_404(Author, lastname=lastname)
        context = {'author':author,}
        return render(request, "file_detail.html", context)

class PostAdminView(View):
    def get(self, request,*args, **kwargs):
        query = self.request.GET.get('q')
        qs = Post.objects.all().order_by("-date_uploaded").search(query)


        if qs.exists():
            return render(request, "file/post_admin.html",{'qs':qs,})
        return render(request, "file/post_admin.html",{'qs':qs,})

class  MemoAdmin(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        file = Memo.objects.all().order_by("-date_uploaded").search(query)

        if file.exists():
            return render(request, "file/memo-admin.html",{'file':file})
        return render(request, "file/memo-admin.html",{'file':file})

def AdminAproval(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = ApprovePostForm(request.POST, instance=post )
        if form.is_valid():           
            post = form.save(commit=False)
            post.save()
        return redirect('file:post-admin')
    else:
        form = ApprovePostForm(instance=Post)
    return render(request, 'file/approve-form.html',{'form': form,
        'post':post})

def MemoApprove(request, pk):
    post = get_object_or_404(Memo, pk=pk)
    if request.method == "POST":
        form = ApproveMemoForm(request.POST, instance=post )
        if form.is_valid():           
            post = form.save(commit=False)
            post.save()
        return redirect('file:memo-admin')
    else:
        form = ApproveMemoForm(instance=Post)
    return render(request, 'file/memo-approve.html',{'form': form,
        'post':post})


def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/file")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

def download_pdf_file(request, filename=''):
    if filename != '':
        # Define Django project base directory
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        # Define the full file path
        filepath = BASE_DIR + '/downloadapp/Files/' + filename
        # Open the file for reading content
        path = open(filepath, 'rb')
        # Set the mime type
        mime_type, _ = mimetypes.guess_type(filepath)
        # Set the return value of the HttpResponse
        response = HttpResponse(path, content_type=mime_type)
        # Set the HTTP header for sending to browser
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        # Return the response value
        return response
    else:
        # Load the template
        return render(request, 'file/file_list.html')

templates/file/file_list.html
{% load static %}
<!DOCTYPE html>
<html lang=en>
  <head> 
    {% include 'snippets/css.html'%}
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/vnd.microsoft.icon">
    <link rel="stylesheet" href="{% static 'css/file.css' %}">
    <link rel="stylesheet" href="{% static 'css/navsnippets.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script> 

    <title>NDMC Archiving</title>
  </head>
     <nav class="navbar navbar-expand-custom navbar-mainbg">
      <img class="ico" alt="Brand" src="{% static '/img/logo.jpeg' %}">
      <h3 class="navbar-brand navbar-logo">NOTRE DAME OF MIDSAYAP COLLEGE
      <br>
      <span>Making a Positive Difference</span></h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
          <li class="nav-item  ">
            <a class="nav-link" href="{% url 'home' %}"><i class="far fa-address-book"></i>Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'file:post' %}"><i class="far fa-address-book"></i>Research Documents</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0);"><i class="far fa-clone"></i>Authors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Departments</a>
          </li>
          {% if user.is_authenticated %}
            {% if request.user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'file:memo' %}"><i class="far fa-chart-bar"></i>Memo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'file:curriculum' %}"><i class="far fa-chart-bar"></i>PAASCU Document</a>
            </li>
            {% endif %}
          {% else %}  
            <li class="nav-item">
              <a class="nav-link"  href='{% url "login" %}'><i class="far fa-copy"></i>Login</a>
            </li>
          {% endif %}
         
        </ul>
      </div>
    </nav>
  <body>
    <div class="page-wrapper chiller-theme toggled">
      <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
      </a>
     {% include 'snippets/sidebar.html'%}
      <div class="container cont">
      <div class="row">
        {% for card in file %}
          {% if card.approve %}
          <div class="col-lg-4 margi-card">
            <div class="card card-margin">
              <div class="card-header no-border">
                <h5 class="card-title"></h5>
              </div>
              <div class="card-body pt-0">
                <div class="widget-49">
                  <div class="widget-49-title-wrapper">
                    <div class="widget-49-date-primary">
                      <span class="widget-49-date-day">{{card.date_uploaded | date:'d' }}</span>
                      <span class="widget-49-date-month">{{card.date_uploaded | date:'b' }}</span>
                    </div>
                    <div class="widget-49-meeting-info">
                      <span class="widget-49-pro-title">{{ card.title }}</span>
                      <span class="widget-49-meeting-time">12:00 to 13.30 Hrs</span>
                    </div>
                  </div>
                    <ol class="widget-49-meeting-points">
                      <li class="widget-49-meeting-item"><span>{{ card.description|truncatewords:"20"|linebreaks }}</span></li>
                    </ol>
                    <div class="download">
                      <a class="link" href='{% url "file:detail"  card.title%}'  >Detail</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </body>
  <a href="#" id="scroll" style="display: none;"><span></span></a>
</html>
<script src="{% static 'js/file.js' %}"></script>
<script src="{% static 'js/navsnippets.js' %}"></script>
{% include 'snippets/js.html' %}

 

templates/file/memo-admin.html
{% load static %}
<!DOCTYPE html>
 
  <head>
    {% include 'snippets/css.html'%}
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/vnd.microsoft.icon">
    <link rel="stylesheet" href="{% static 'css/navsnippets.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script> 
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
    <title>NDMC Archiving</title>
  </head>
 <nav class="navbar navbar-expand-custom navbar-mainbg">
  <img class="ico" alt="Brand" src="{% static '/img/logo.jpeg' %}">
  <h3 class="navbar-brand navbar-logo">NOTRE DAME OF MIDSAYAP COLLEGE
  <br>
  <span>Making a Positive Difference</span></h3>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <i class="fas fa-bars text-white"></i>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
      <li class="nav-item  ">
        <a class="nav-link" href="{% url 'home' %}"><i class="far fa-address-book"></i>Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'file:post' %}"><i class="far fa-address-book"></i>Research Documents</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="javascript:void(0);"><i class="far fa-clone"></i>Authors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Departments</a>
      </li>
      {% if user.is_authenticated %}
        {% if request.user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'file:memo' %}"><i class="far fa-chart-bar"></i>Memo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'file:curriculum' %}"><i class="far fa-chart-bar"></i>PAASCU Document</a>
        </li>
        {% endif %}
      {% else %}  
        <li class="nav-item">
          <a class="nav-link"  href='{% url "login" %}'><i class="far fa-copy"></i>Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
<body>
  <div class="marg">
      <div class="page-wrapper chiller-theme toggled">
      <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
      </a>
     {% include 'snippets/sidebar.html'%}
     <div class="players">
        <h2> Memorandum  | List</h2>
        <div class="header">
          <div class="player-number">ID Number</div>
          <div class="player-name">Title</div>
          <div class="player-city">Uploaded By</div>
          <div class="player-value">Date Uploaded </div>
        </div>
        {% for qs in file %}
        <div class="player">
          <div class="player-number" data-title="Number: ">{{qs.pk }}</div>
          <div class="player-name" data-title="Name: "> <a  class="link" href="{% url "file:memo-approve" qs.pk%}">
            {{qs.title}}</a>
          </div>
          <div class="player-city" data-title="City: ">
            {{qs.user}}</div>
          <div class="player-value" data-title="Value: ">
            {{qs.date_uploaded}}</div> 
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</body>
<script src="{% static 'js/file.js' %}"></script>
<script src="{% static 'js/navsnippets.js' %}"></script>
{% include 'snippets/js.html' %}
 
 
</html>
 

templates/file/memo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  {% include 'snippets/css.html'%}
  <meta charset="utf-8">
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/vnd.microsoft.icon">
  <link rel="stylesheet" href="{% static 'css/memo.css' %}">
  <link rel="stylesheet" href="{% static 'css/navsnippets.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script> 
  <title>NDMC Archiving</title>
</head>
     <nav class="navbar navbar-expand-custom navbar-mainbg">
      <img class="ico" alt="Brand" src="{% static '/img/logo.jpeg' %}">
      <h3 class="navbar-brand navbar-logo">NOTRE DAME OF MIDSAYAP COLLEGE
      <br>
      <span>Making a Positive Difference</span></h3>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	       <i class="fas fa-bars text-white"></i>
	    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
          <li class="nav-item  ">
            <a class="nav-link" href="{% url 'home' %}"><i class="far fa-address-book"></i>Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'file:post' %}"><i class="far fa-address-book"></i>Research Documents</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0);"><i class="far fa-clone"></i>Authors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Departments</a>
          </li>
          {% if user.is_authenticated %}
            {% if request.user.is_staff %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'file:memo' %}"><i class="far fa-chart-bar"></i>Memo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'file:curriculum' %}"><i class="far fa-chart-bar"></i>PAASCU Document</a>
            </li>
            {% endif %}
          {% else %}  
            <li class="nav-item">
              <a class="nav-link"  href='{% url "login" %}'><i class="far fa-copy"></i>Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  <body>
    <div class="page-wrapper chiller-theme toggled">
      <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
      </a>
     {% include 'snippets/sidebar.html'%}
      <div class="tweets-container">
        <div class="card tweets-header">
          Memorandum
        </div>
        {% for qs in file %}
        {% if qs.approve %}
        <div class="card tweet">
          <a class="author">
            <img class="avatar" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg">
            <span class="name">{{ qs.user.first_name }} {{ card.user.last_name }}</span>
            <span class="username">{{ qs.user.email}} </span>
          </a>
          <div class="content">
            <small>{{ qs.date_uploaded  | timesince }}, ago </small> 
          </div>
          <div class="card summary">
            <img class="background"  src="{{qs.content.url }}" />
            <div class="information">
              <div class="title">{{ qs.title}} </div>
              <div class="description">
                {{ qs.description|truncatewords:"20"|linebreaks }}
              </div>
              <div class="domain">
                <a class="link" href='{% url "file:memo-detail"  qs.title%}'  >Detail</a>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      {% endfor %}
    </div>
  </body>
</html>
<script src="{% static 'js/file.js' %}"></script>
<script src="{% static 'js/navsnippets.js' %}"></script>
{% include 'snippets/js.html' %}
 