account/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns = [
    path('', views.ProfileView.as_view(), name='user'),
    path('profile/', views.ProfileAdminView.as_view(), name='user-admin'),
    path('faculty/', views.FacultyView.as_view(), name='faculty'),
    path('student/', views.StudentView.as_view(), name='student'),
    path('program_head/', views.ProfileView.as_view(), name='program'),
    path('profiles/', views.ProgramView.as_view(), name='profile'),
    path('<email>/', views.ProfileDetailView.as_view(), name='detail'),
    path('profile/edit/<int:pk>/', views.EditProfileView, name='edit_profile'),
    path('profile/assign/<email>/', views.Ruleassign, name='assign_profile'),
    path('password/edit/<id_number>/', views.EditPassword.as_view(), name='edit_password'),
]

archive/urls.py
from django.contrib import admin
from django.urls import path
from file.views import HomeView
from django.conf import settings
from django.urls import path, include, reverse_lazy
from account.views import LoginView, RegisterView 
from django.contrib.auth.views import  LogoutView
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('account/', include('account.urls', namespace='user')),
    path('file/', include('file.urls', namespace='file')),
 
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('register/',RegisterView.as_view(), name='register'),
 
]
urlpatterns.extend(
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

file/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.static import serve
from . import views

app_name='file'

urlpatterns = [
    path('', views.PostView.as_view(), name='post'),
    path('admin-list/', views.PostAdminView.as_view(), name='post-admin'),
    path('memo/', views.Memorandum.as_view(), name='memo'),
    path('memo-admin/', views.MemoAdmin.as_view(), name='memo-admin'),
    path('curriculum/', views.Curriculum.as_view(), name='curriculum'),
    path('Syllabus', views.Syllabus.as_view(), name='syllabus'),
    path('<title>/', views.PostDetailView.as_view(), name='detail'),
    path('memo/<title>/', views.MemoDetailView.as_view(), name='memo-detail'),
    path('approve-file/<int:pk>/', views.AdminAproval, name='file-approve'),
    path('approve-memo/<int:pk>/', views.MemoApprove, name='memo-approve'),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
   
#    path('post/', views.PdfUploadView.as_view(), name='post')
]

templates/snippets/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.css.map' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css.map' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="{% static 'css/nav.css' %}">
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/carousel.css' %}">

templates/snippets/js.html
{% load static %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js.map' %}"></script>
<script src="{% static 'js/bootstrap.min.js.map' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="{% static 'js/bootstrap.bundle.js.map' %}"></script>
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/home.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script> 
<script src="{% static 'js/carousel.js' %}"></script>
<script src="{% static 'js/login.js' %}"></script>

 

templates/snippets/modal.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

templates/snippets/nav.html
{% include 'snippets/css.html'%}

  <nav class="navbar navbar-expand-custom navbar-mainbg">
      <img class="ico" alt="Brand" src="{% static '/img/logo.jpeg' %}">
      <h3 class="navbar-brand navbar-logo">NOTRE DAME OF MIDSAYAP COLLEGE
      <br>
      <span>Making a Positive Difference</span></h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'file:post' %}"><i class="far fa-address-book"></i>Research Documents</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0);"><i class="far fa-clone"></i>Authors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Departments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0);"><i class="far fa-chart-bar"></i>Memo</a>
          </li>
              {% if user.is_authenticated %}
                {% if request.user.is_staff %}
                  <li><a href=" " class="user">Reserve List</a></li>
                  <li><a href=" ">Reserved Books</a></li>
                  <li><a href='{% url "logout" %}'><span>Logout<span></a></li>
                {% else %}
                  <li><a href='{% url "user:detail" user.email %}' class="user">{{ user.email}}</a></li>
                  <li><a href='{% url "logout" %}'><span>Logout<span></a></li>
                {% endif %}
              {% else %}  
            <li class="nav-item">
              <a class="nav-link"  href='{% url "login" %}'><i class="far fa-copy"></i>Login</a>
            </li>
          {% endif %}
         
        </ul>
      </div>
    </nav>
  {% include 'snippets/js.html' %}

templates/snippets/sidebar.html
      <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">
          <div class="sidebar-brand">
            <a href="#">pro sidebar</a>
            <div id="close-sidebar">
              <i class="fas fa-times"></i>
            </div>
          </div>
          <div class="sidebar-header">
          {% if user.is_authenticated %}
              {% if request.user.is_staff %}
                <div class="user-pic">
                  <img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                    alt="User picture">
                </div>
                <div class="user-info">
                  <span class="user-name">{{ user.first_name}}
                    <strong> {{ user.last_name}}</strong>
                  </span>
                  <span class="user-role">Administrator</span>
                  <span class="user-status">
                    <i class="fa fa-circle"></i>
                    <span>Online</span>
                  </span>
                </div>
                 {% else %}
                  <div class="user-pic">
                  <img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                    alt="User picture">
                </div>
                <div class="user-info">
                  <span class="user-name">{{ user.first_name}}
                    <strong>{{ user.last_name}}</strong>
                  </span>
                 
                  <span class="user-role">Students</span>
                  <span class="user-status">
                    <i class="fa fa-circle"></i>
             
                    <span>Online</span>
                  </span>
                </div>
              {% endif %}
            {% endif %}
          </div>
          <!-- sidebar-header  -->
          <div class="sidebar-search">
            <div>
                    <form class='form' method='GET' action='.'>
              <div class="input-group">
                <input type="text" class="form-control search-menu" placeholder="Search..." name='q' value='{{ request.GET.q }}'>
                <div class="input-group-append">
                  <span class="input-group-text">
                         <button class='fa fa-search' aria-hidden="false" type='submit'></button> 
                  </span>
                </div>
              </div>
            </form>
            </div>
          </div>
          <div class="sidebar-menu">
            {% if user.is_authenticated %}
              {% if request.user.is_staff %}
            <ul>
              <li class="header-menu">
                <span>General</span>
              </li>
              <li class="sidebar-dropdown">
                <a href="#">
                  <i class="fa fa-tachometer-alt"></i>
                  <span>User List</span>
              
                </a>
                <div class="sidebar-submenu">
                  <ul>
                    <li>
                      <a href="{% url 'account:faculty' %}">Faculty
                        <span class="badge badge-pill badge-success">Pro</span>
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'account:student' %}">Student</a>
                    </li>
                    <li>
                      <a href="#">Program Head</a>
                    </li>
                  </ul>
                </div>
              </li>
              <li class="sidebar-dropdown">
                <a href="#">
                  <i class="fa fa-shopping-cart"></i>
                  <span>File</span>
                  <span class="badge badge-pill badge-danger">3</span>
                </a>
                <div class="sidebar-submenu">
                  <ul>
                    <li>
                      <a href="#">File 

                      </a>
                    </li>
                    <li>
                      <a href="#">Author</a>
                    </li>
 
                  </ul>
                </div>
              </li>
             <li class="header-menu">
                <span>Components</span>
              </li>
              <li class="sidebar-dropdown">
                <a href="#">
                  <i class="fa fa-chart-line"></i>
                  <span>User Approval</span>
                </a>
                <div class="sidebar-submenu">
                  <ul>
                    <li>
                      <a href="{% url 'account:user-admin' %}">User</a>
                    </li>
                    <li>
                      <a href="{% url 'file:post-admin' %}">File</a>
                    </li>
                    <li>
                      <a href="{% url 'file:memo-admin' %}">Memo</a>
                    </li>
                  </ul>
                </div>
              </li>
              <li class="sidebar-dropdown">
                <a href="#">
                  <i class="fa fa-globe"></i>
                  <span>Maps</span>
                </a>
                <div class="sidebar-submenu">
                  <ul>
                    <li>
                      <a href="#">Google maps</a>
                    </li>
                    <li>
                      <a href="#">Open street map</a>
                    </li>
                  </ul>
                </div>
              </li>
              <li class="header-menu">
                <span>Extra</span>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-book"></i>
                  <span>Documentation</span>
                  <span class="badge badge-pill badge-primary">Beta</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-calendar"></i>
                  <span>Calendar</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-folder"></i>
                  <span>Examples</span>
                </a>
              </li>
            </ul>
            {% else %}
          <ul>
          <li class="header-menu">
            <span>General</span>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-tachometer-alt"></i>
              <span> User List</span>
            </a>
 
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-shopping-cart"></i>
              <span><strong>{{ user.email}}</strong></span>
            </a>
 
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="far fa-gem"></i>
              <span>Components</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">General</a>
                </li>
                <li>
                  <a href="#">Panels</a>
                </li>
                <li>
                  <a href="#">Tables</a>
                </li>
                <li>
                  <a href="#">Icons</a>
                </li>
                <li>
                  <a href="#">Forms</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-chart-line"></i>
              <span>Edit Profile</span>
            </a>
 
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-globe"></i>
              <span>Change Password</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Google maps</a>
                </li>
                <li>
                  <a href="#">Open street map</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="header-menu">
            <span>Extra</span>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-book"></i>
              <span>Documentation</span>
              <span class="badge badge-pill badge-primary">Beta</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-calendar"></i>
              <span>Calendar</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-folder"></i>
              <span>Examples</span>
            </a>
          </li>
        </ul>  
              {% endif %}
            {% endif %}
        </div>
        <div class="sidebar-footer">
          <a href="#">
            <i class="fa fa-bell"></i>
            <span class="badge badge-pill badge-warning notification">3</span>
          </a>
          <a href='{% url "logout" %}'>
            <i class="fa fa-power-off"></i>
          </a>
        </div>
      </div>
    </nav>
    
    {% include 'snippets/js.html' %}