archive/urls.py
from django.contrib import admin
from django.urls import path
from file.views import HomeView
from django.conf import settings
from django.urls import path, include, reverse_lazy
from account.views import LoginView, RegisterView 
from django.contrib.auth.views import  LogoutView
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('account/', include('account.urls', namespace='user')),
    path('file/', include('file.urls', namespace='file')),
 
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('register/',RegisterView.as_view(), name='register'),
 
]
urlpatterns.extend(
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

file/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.static import serve
from . import views

app_name='file'

urlpatterns = [
    path('', views.PostView.as_view(), name='post'),
    path('admin-list/', views.PostAdminView.as_view(), name='post-admin'),
    path('memo/', views.Memorandum.as_view(), name='memo'),
    path('memo-admin/', views.MemoAdmin.as_view(), name='memo-admin'),
    path('curriculum/', views.Curriculum.as_view(), name='curriculum'),
    path('Syllabus', views.Syllabus.as_view(), name='syllabus'),
    path('<title>/', views.PostDetailView.as_view(), name='detail'),
    path('memo/<title>/', views.MemoDetailView.as_view(), name='memo-detail'),
    path('approve-file/<int:pk>/', views.AdminAproval, name='file-approve'),
    path('approve-memo/<int:pk>/', views.MemoApprove, name='memo-approve'),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
   
#    path('post/', views.PdfUploadView.as_view(), name='post')
]

templates/footer.html
    {% include 'snippets/css.html'%}
  <div class="footer-dark">
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-md-3 item">
            <h3>Services</h3>
            <ul>
            <li><a href="#">Web design</a></li>
            <li><a href="#">Development</a></li>
            <li><a href="#">Hosting</a></li>
            </ul>
          </div>
          <div class="col-sm-6 col-md-3 item">
            <h3>About</h3>
            <ul>
            <li><a href="#">Company</a></li>
            <li><a href="#">Team</a></li>
            <li><a href="#">Careers</a></li>
            </ul>
          </div>
          <div class="col-md-6 item text">
            <h3>Company Name</h3>
            <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
          </div>
          <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
        </div>
        <p class="copyright">Archiving © 2021</p>
      </div>
    </footer>
  </div>
  {% include 'snippets/js.html' %}

templates/home.html
{% load static %}
<!DOCTYPE html>
  <html lang=en>
  <head> 
    {% include 'snippets/css.html'%}
    <title>Archiving</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/vnd.microsoft.icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/file_list.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="{% static 'js/home.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <title>NDMC Archiving</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-custom navbar-mainbg">
      <img class="ico" alt="Brand" src="{% static '/img/logo.jpeg' %}">
      <h3 class="navbar-brand navbar-logo">NOTRE DAME OF MIDSAYAP COLLEGE
      <br>
      <span>Making a Positive Difference</span></h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
          <li class="nav-item active ">
            <a class="nav-link" href="{% url 'home' %}"><i class="far fa-address-book"></i>Home</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="{% url 'file:post' %}"><i class="far fa-address-book"></i>Research Documents</a>
          </li>
          {% if user.is_authenticated %}
            {% if request.user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'file:memo' %}"><i class="far fa-chart-bar"></i>Memo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'file:curriculum' %}"><i class="far fa-chart-bar"></i>PAASCU Document</a>
              <li><a href='{% url "logout" %}'><span>Logout<span></a></li>
            </li>
          {% else %}
            <li><a href='{% url "user:detail" user.email %}' class="user">{{ user.email}}</a></li>
            <li><a href='{% url "logout" %}'><span>Logout<span></a></li>
          {% endif %}
          {% else %}  
            <li class="nav-item">
              <a class="nav-link"  href='{% url "login" %}'><i class="far fa-copy"></i>Login</a>
            </li>
          {% endif %}
         
        </ul>
      </div>
    </nav>
    <div class="carousel slide" id="demo-carousel" data-ride="carousel">
      <ol class="carousel-indicators">
        <li class="active" data-target="#demo-carousel" data-slide-to="1"></li>
        <li data-target="#demo-carousel" data-slide-to="2"></li>
        <li data-target="#demo-carousel" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active" data-src="{% static 'img/carousel.jpeg' %}">
          <div class="carousel-caption">
            <h3>Test caption 1</h3>
            <p>Test caption description 1</p>
          </div>
        </div>
        <div class="carousel-item" data-src="{% static 'img/carousel2.jpeg' %}">
          <div class="carousel-caption">
            <h3>Test caption 2</h3>
            <p>Test caption description 2</p>
          </div>
        </div>
        <div class="carousel-item" data-src="{% static 'img/car.jpeg' %}">
          <div class="carousel-caption">
            <h3>Test caption 3</h3>
            <p>Test caption description 3</p>
          </div>
        </div>
      </div><a class="left carousel-control" href="#demo-carousel" role="button" data-slide="prev"><span class="icon-prev" aria-hidden="true</span><span class="sr-only"> </span></a><a class="right carousel-control" href="#demo-carousel" role="button" data-slide="next"><span class="icon-next" aria-hidden="true"></span><span class="sr-only">Next</span></a>
    </div>
 <div class="container cont">
  <div class="row">
          {% for card in file %}
      <div class="col-lg-3">
   
          <div class="card card-margin">
              <div class="card-header no-border">
                  <h5 class="card-title"></h5>
              </div>
              <div class="card-body pt-0">
                  <div class="widget-49">
                      <div class="widget-49-title-wrapper">
                          <div class="widget-49-date-primary">
                              <span class="widget-49-date-day">09</span>
                              <span class="widget-49-date-month">apr</span>
                          </div>
                          <div class="widget-49-meeting-info">
                              <span class="widget-49-pro-title">{{ card.title }}</span>
                              <span class="widget-49-meeting-time">12:00 to 13.30 Hrs</span>
                          </div>
                      </div>
                      <ol class="widget-49-meeting-points">
                          <li class="widget-49-meeting-item"><span>{{ card.description|truncatewords:"20"|linebreaks }}</span></li>
 
                      </ol>
 
                  </div>
              </div>
          </div>
      </div>

          {% endfor %}
  </div>
</div>
  </body>
  </body>
  <a href="#" id="scroll" style="display: none;"><span></span></a>
  <div class="footer-dark">
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-md-3 item">
            <h3>Services</h3>
            <ul>
            <li><a href="#">Web design</a></li>
            <li><a href="#">Development</a></li>
            <li><a href="#">Hosting</a></li>
            </ul>
          </div>
          <div class="col-sm-6 col-md-3 item">
            <h3>About</h3>
            <ul>
            <li><a href="#">Company</a></li>
            <li><a href="#">Team</a></li>
            <li><a href="#">Careers</a></li>
            </ul>
          </div>
          <div class="col-md-6 item text">
            <h3>Company Name</h3>
            <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
          </div>
          <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
        </div>
        <p class="copyright">Archiving © 2021</p>
      </div>
    </footer>
  </div>
</html>
{% include 'snippets/js.html' %}

 

templates/memo.html
<!DOCTYPE html>
<html>
<head>
	<title> NDMC | Memo </title>
</head>
<body>

</body>
</html>>